[ef] Fix problem with includes
The non required `Unit` caused a warning.
When an attribute, such as `PersonsUnits` is used multiple times,
the must be consecutive, to avoid this error:

  System.InvalidOperationException: An error was generated for warning
  'Microsoft.EntityFrameworkCore.Query.NavigationBaseIncludeIgnored':
  The navigation 'PersonStatisticalUnit.Unit' was ignored from 'Include'
  in the query since the fix-up will automatically populate it.
  If any further navigations are specified in 'Include' afterwards then
  they will be ignored. Walking back include tree is not allowed.
  This exception can be suppressed or logged by passing event ID
  'CoreEventId.NavigationBaseIncludeIgnored' to the 'ConfigureWarnings'
  method in 'DbContext.OnConfiguring' or 'AddDbContext'.